---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен отображать список товаров с детальной информацией (название, рейтинг, цена со скидкой и без)
  - Сайт должен иметь постраничный вывод товаров для управления объемом данных на экране
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность добавить товар в корзину и продолжить выбирать товары в каталоге
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Приложение должно работать без перезагрузки страниц
  - Интерфейс должен быть удобным и корректно отображаться на мобильных устройствах
  - Данные корзины должны храниться в рамках текущей сессии браузера
implicit:
  - Пользователь не может редактировать описание товара
  - Обновление количества товаров в шапке (мини-корзине) мгновенно после добавления товара в каталог, без перезагрузки
  - При возврате из карточки товара в каталог, пользователь должен оказаться на том же месте в списке, где он остановился
  - Обязательное наличие спиннеров при ожидании данных от API, чтобы интерфейс не выглядел зависшим
  - Показ уведомлений, если запрос к серверу не удался (например, при попытке добавить товар в корзину без интернета)
  - Система должна проверять наличие товара на складе перед добавлением в корзину или переходом к оплате
